### ISSUE TITLE
[SONG REQUEST] M83 - Outro

### ISSUE THREAD

**Issue by safeishsalamander12** [knijn/musicify#28]
## The song name and artist:
M83 - Outro

## Links to the song
https://www.youtube.com/watch?v=eSPCeHbhScU

**Comment by RubenHetKonijn** [comment]
Do you want me to cut it to the song part or what do you want me to do? there's alot of silence in the beginning in the link that you sent me

**Comment by Sebsprite** [comment]
im freinds with safe i say just send do the whole song he likes the silence
