### ISSUE TITLE
[BUG] Autoupdater not working as expected

### ISSUE THREAD

**Issue by Erb3** [knijn/musicify#44]
**Describe the bug**
I tried to setup Musicify on 1.18. Instead of coming up with a error when running `musicify`, it instead prompted me with a broken autoupdater.

**To Reproduce**
1. Launch Minecraft with Fabric 1.18.1 and CC:R 1.100.2
2. Follow the readme, and download musicify with the help of `wget run https://raw.githubusercontent.com/knijn/musicify/main/install.lua`
3. Run `musicify` in the computer

**Expected behavior**
That the musicify error menu comes up.
> Please provide a valid command. For usage, use `musicify help`.

**Screenshots**
![image](https://user-images.githubusercontent.com/49862976/197778874-98217c4e-fa0c-43c8-aeef-78c417855376.png)
![image](https://user-images.githubusercontent.com/49862976/197778956-69aa90e4-1923-4054-8123-294c187ef485.png)

**Setup:**
 - Type of Computer: Advanced Computer
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 2.0.0

**Comment by EmmaKnijn** [comment]
Fixed in 2.1
