### ISSUE TITLE
Youcube is broken

### ISSUE THREAD

**Issue by Mifluxlevelux** [knijn/musicify#57]
**Describe the bug**
it’s a small error that prevents youcube execution, it gives error 404

**To Reproduce**

1. Go to 'computer'
2. type 'musificy youcube [LINK]'
3. See error

**Expected behavior**
I just wanted to play the fight music with the dragon place 

**Setup**

- Type of Computer: [Advanced Computer]
- Version [CraftOS 1.8]

**Comment by Commandcracker** [comment]
musificy is only using the fallback server and the fallback failed to deploy

**Comment by Commandcracker** [comment]
The fallback server is now up and running!
Somehow the server failed to deploy without an error message, looks like onrender.com fucked up. -_-
i just ran the same deployment again and it worked.

**Comment by Mifluxlevelux** [comment]
Thanks for that, now it's working, normaly ?? it take 10 minutes to request the song but now it working with the best sound experience i ever seen (im french so my english is a little bit bad)

**Comment by Mifluxlevelux** [comment]
> Thanks for that, now it's working, normaly ?? it take 10 minutes to request the song but now it working with the best sound experience i ever seen (im french so my english is a little bit bad)

And how we expand the sound boarder ?

**Comment by Commandcracker** [comment]
> Thanks for that, now it's working, normaly ?? it take 10 minutes to request the song but now it working with the best sound experience i ever seen (im french so my english is a little bit bad)

It should work normally. It takes 10 minutes to request because musicify is currently using the fallback server. You can change the server by adding it at the top of the server table in libs/youcube.lua, The ip of the primary server is [ws://oxygen.knijn.one:5000](https://commandcracker.github.io/YouCube/)
The request time also depends on the song length.

**Comment by Commandcracker** [comment]
> And how we expand the sound boarder ?

I don't understand your question.

**Comment by Mifluxlevelux** [comment]
I mean how to increase the listening distance, currently it is 15 it seems to me but we would like to increase it to 30/40

**Comment by Commandcracker** [comment]
Its limited to the CC: Tweaked Speaker. To cover a greater distance YouCube will soon support connecting multiple speakers to the computer but for now you could use a noisy pocket computer.

**Comment by EmmaKnijn** [comment]
I'll fix this

**Comment by EmmaKnijn** [comment]
Fixed in 2.3.2
