### ISSUE TITLE
[FEATURE] libs to lib

### ISSUE THREAD

**Issue by Commandcracker** [knijn/musicify#61]
**Description**

Changing form "libs" to "lib" might be a good idea, because its moor common (for example Linux is placing lib's in /lib) and
unicornpkg places lib's in "/lib" this in why musicify is currently not compatible with unicornpkg.
using an Library loader like [OpenLibrarieLoader](https://github.com/Commandcracker/YouCube/blob/f9aa58f0fcfac03c899272ffb12419a2a213076f/client/youcube.lua#L11-L49) is also and solution.

**Comment by EmmaKnijn** [comment]
Fixed in 2.5.0
