### ISSUE TITLE
[BUG] Release v2.5.0 two file extensions

### ISSUE THREAD

**Issue by Commandcracker** [knijn/musicify#62]
**Describe the bug**
`musicify.lua.txt` has the file extension `.lua` and `.txt`, it should only be `musicify.lua`.
_You made a small oops_
(You can use the edit release functionality to fix this)

![Screenshot_20221115_160015](https://user-images.githubusercontent.com/49335821/201952136-82104569-37e6-480e-b6f4-1d2f642f68f1.png)

**Comment by EmmaKnijn** [comment]
Apparently the GitHub release editor doesn't remove the file extension when you remove it in the text box, Fixed it now
