### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dzeima** [knijn/musicify#74]
**Describe the bug**
might be not on your side but can't get youcube working. 

**To Reproduce**
musicify youcube <url>

1. Go to 'computer'
2. Click on 'computer'
3. type musicify youcube <url>
4. wait 1-3mins
5. See error

**Expected behavior**
would read YT url and then extract audio convert it into correct format and then paly yhe audio

**Screenshots**

**Setup (please complete the following information):**
4 monitors n speakers
![Screenshot_156](https://github.com/knijn/musicify/assets/112252451/c13f86a7-df76-4eed-bcf9-d8e90c95bdc0)
![Screenshot_157](https://github.com/knijn/musicify/assets/112252451/12b43d35-5935-4424-8f9b-6cd37563f278)
![Screenshot_158](https://github.com/knijn/musicify/assets/112252451/9e5965b9-b32d-40f8-af14-3bba124e0d05)
![Screenshot_159](https://github.com/knijn/musicify/assets/112252451/4cdc32c0-4b35-4967-a022-7d490ef2f475)

- Type of Computer: [e.g. Advanced Computer]
- Version 1.20.1 CC-1.111.0

**Additional context**

**Comment by EmmaKnijn** [comment]
YouCube support has been removed, have a look at the new URL command, and see if it suits your needs. Playback on multiple connected speakers also might not work as you expect, by the way.

Sorry for the late response
